name: Build & Publish to GCP

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  IMAGE_URL: europe-west3-docker.pkg.dev/viadee-clusters/docker-dev/bpm-dev/quarkus-example-worker

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_REGISTRY_SA_KEY }}
          project_id: ${{ secrets.GCP_REGISTRY_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker europe-west3-docker.pkg.dev
      # Build JAR for Docker image
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file example/example-worker/pom.xml
      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --file example/example-worker/src/main/docker/Dockerfile.jvm \
            --tag "$IMAGE_URL:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "$IMAGE_URL:$GITHUB_SHA"