name: Build & Publish to GCP

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  IMAGE_URL: europe-west3-docker.pkg.dev/viadee-clusters/docker-dev/bpm-dev/quarkus-example-engine

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_REGISTRY_SA_KEY }}
          project_id: ${{ secrets.GCP_REGISTRY_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker europe-west3-docker.pkg.dev
      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            -f example-engine/src/main/docker/Dockerfile.jvm
            --tag "$IMAGE_URL:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "$IMAGE_URL:$GITHUB_SHA"